<?php

return [
    'cities' => [
        'London',
        'Birmingham',
        'Manchester',
        'Liverpool',
        'Leeds',
        'Sheffield',
        'Bristol',
        'Newcastle upon Tyne',
        'Nottingham',
        'Leicester',
        'Coventry',
        'Hull',
        'Bradford',
        'Stoke-on-Trent',
        'Wolverhampton',
        'Derby',
        'Swansea',
        'Southampton',
        'Portsmouth',
        'Glasgow',
        'Edinburgh',
        'Cardiff',
        'Belfast',
        'Aberdeen',
        'Dundee',
        'Inverness',
        'Stirling',
        'York',
        'Bath',
        'Cambridge',
        'Oxford',
        'Brighton',
        'Reading',
        'Milton Keynes',
        'Norwich',
        'Exeter',
        'Plymouth',
        'Swindon',
        'Preston',
        'Lancaster',
    ],
];
